@TurismoWeb.Server_HostAddress = https://localhost:7026

GET {{TurismoWeb.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TurismoWeb.Server_HostAddress}}/weatherforecast

###
